# Generated by Django 3.2 on 2023-07-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Contactnumber',
            new_name='contactnumber',
        ),
    ]
